CREATE DATABASE IF NOT EXISTS sa CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sa;

CREATE TABLE IF NOT EXISTS user_table (
    Name VARCHAR(32) BINARY NOT NULL,
    Pass VARCHAR(32) NOT NULL,
    RegTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Path VARCHAR(64) NOT NULL DEFAULT '',
    LoginTime DATETIME NULL,
    PRIMARY KEY (Name)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_lock (
    Name VARCHAR(64) BINARY NOT NULL,
    PRIMARY KEY (Name)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

INSERT INTO user_table (Name, Pass, Path)
VALUES ('stoneage', 'stoneage', 'char/0x0')
ON DUPLICATE KEY UPDATE Pass = VALUES(Pass);
